name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run tests using Docker Compose
      run: npm run test:docker
    
    - name: Cleanup
      if: always()
      run: |
        docker compose -f docker-compose.test.yml down
        docker rm -f todo-mysql-test || true

  # 新增：保存 PR 描述到 Google Drive（僅在 PR 事件時執行）
  save-pr-description:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Generate PR description file
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const branch = pr.head.ref;
            const filename = `${branch}.md`;
            const header = `# PR #${pr.number} - ${pr.title}\n\n`;
            const body = pr.body || "_(no description)_";
            const fs = require('fs');
            fs.writeFileSync(filename, header + body + "\n");
            core.info(`Generated ${filename}`);

      - name: Install rclone
        run: curl https://rclone.org/install.sh | bash

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          cat <<EOF > ~/.config/rclone/rclone.conf
          [gdrive]
          type = drive
          scope = drive.file
          token = ${{ secrets.RCLONE_TOKEN }}
          EOF

      - name: Upload to Google Drive
        run: |
          BRANCH="${{ github.event.pull_request.head.ref }}"
          SAFE_BRANCH=$(echo "$BRANCH" | sed 's/[\/:]/-/g')
          rclone copy "${BRANCH}.md" "gdrive:GitHub-PR-Descriptions/${SAFE_BRANCH}.md"

      - name: Cleanup
        run: rm "${{ github.event.pull_request.head.ref }}.md"