name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: [self-hosted, Linux, ARM64]

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: todo_test_db
          MYSQL_ROOT_HOST: "%"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -ppassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Verify MySQL connection
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client
        echo "檢查 MySQL 連接..."
        mysql -h 127.0.0.1 -P 3306 -u root -ppassword -e "SHOW DATABASES;"
    
    - name: Setup test data
      run: npm run setup-test-data
      env:
        NODE_ENV: test
        DB_HOST: 127.0.0.1
        DB_USER: root
        DB_PASSWORD: password
        DB_NAME: todo_test_db
    
    - name: Run tests
      run: npm test
      env:
        NODE_ENV: test
        DB_HOST: 127.0.0.1
        DB_USER: root
        DB_PASSWORD: password
        DB_NAME: todo_test_db