name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: [self-hosted, Linux, ARM64]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run tests using Docker Compose
      run: npm run test:docker
    
    - name: Cleanup
      if: always()
      run: |
        docker compose -f docker-compose.test.yml down
        docker rm -f todo-mysql-test || true